"""Generator Agent — proposes content based on GH events.

The generator watches the SuperInstance and purplepincher github orgs for
notable events (PRs, releases, doctrine updates, witness emissions). For each
event, it proposes a content update to the site.

Doctrine (Sept 23, 2026):
- Every proposal has a witness (the GH event IS the witness)
- Every proposal is staged as a PR with a clear receipted subject
- The Adversary Agent reviews; humans approve
- The site is alive — proposals arrive within 24 hours of GH events

This is the GAN loop applied to a documentation surface.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


@dataclass
class GHEvent:
    """A github event to react to."""
    event_type: str  # 'pr_opened', 'pr_merged', 'release', 'issue_opened', 'comment_added', 'witness_emitted'
    repo: str  # e.g., 'SuperInstance/quilt-port'
    title: str
    url: str
    body: str = ""
    actor: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat() + "Z")


@dataclass
class ContentProposal:
    """A proposed content update for the site."""
    proposal_id: str
    target_path: str  # e.g., 'site/fleet/quilt-port/index.html'
    title: str
    body: str  # the proposed content
    source_event: GHEvent
    kind: str  # 'fleet_entry', 'doctrine_clarification', 'changelog_entry', 'press_kit_update'
    witnesses: List[str] = field(default_factory=list)  # citations
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat() + "Z")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "target_path": self.target_path,
            "title": self.title,
            "body": self.body,
            "source_event": self.source_event.__dict__,
            "kind": self.kind,
            "witnesses": self.witnesses,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }


class Generator:
    """The GAN Generator.

    Watches GH events. Proposes content. Stages as PR.
    """

    def __init__(self, gh_token: Optional[str] = None, orgs: Optional[List[str]] = None):
        self.gh_token = gh_token
        self.orgs = orgs or ["SuperInstance", "purplepincher"]
        self.proposals: List[ContentProposal] = []

    def watch(self, since: Optional[str] = None) -> List[GHEvent]:
        """Watch GH orgs for events since `since` (ISO timestamp).

        Returns a list of GHEvent objects to react to.
        """
        # In production: paginate GH API for events.
        # For v0.1: returns an empty list; the orchestrator passes events explicitly.
        return []

    def propose_fleet_entry(self, event: GHEvent) -> ContentProposal:
        """Generate a fleet page proposal for a repo event."""
        # Strip org prefix for path
        repo_name = event.repo.split("/")[-1]
        target = f"site/fleet/{repo_name}/index.html"
        body = (
            f"# {repo_name}\n\n"
            f"## What it does\n\n"
            f"{event.body or 'See the github repo for description.'}\n\n"
            f"## Hull Doctrine role\n\n"
            f"Tagged: TBD by Adversary.\n\n"
            f"## Why it matters\n\n"
            f"(Auto-generated by the GAN pipeline. Adversary review pending.)\n\n"
            f"## Witness\n\n"
            f"- Source: [{event.repo}@{event.timestamp}]({event.url})\n"
            f"- Generator: mavis-pipeline-generator v0.1\n"
            f"- FNV1a-64 canary: 0x24a555471370b18d\n"
        )
        proposal = ContentProposal(
            proposal_id=f"prop-{int(datetime.now(timezone.utc).timestamp())}-{repo_name}",
            target_path=target,
            title=f"Fleet entry: {repo_name}",
            body=body,
            source_event=event,
            kind="fleet_entry",
            witnesses=[event.url],
        )
        self.proposals.append(proposal)
        return proposal

    def propose_changelog_entry(self, event: GHEvent) -> ContentProposal:
        """Generate a changelog entry proposal."""
        date = event.timestamp[:10]
        target = f"site/changelog/{date}-{event.repo.replace('/', '-')}.html"
        body = (
            f"# {event.title}\n\n"
            f"{event.body or '(Auto-generated.)'}\n\n"
            f"## Witnesses\n\n"
            f"- Source: [{event.repo}@{event.timestamp}]({event.url})\n"
        )
        proposal = ContentProposal(
            proposal_id=f"prop-{int(datetime.now(timezone.utc).timestamp())}-changelog",
            target_path=target,
            title=f"Changelog: {event.title}",
            body=body,
            source_event=event,
            kind="changelog_entry",
            witnesses=[event.url],
        )
        self.proposals.append(proposal)
        return proposal

    def propose_doctrine_update(self, event: GHEvent) -> ContentProposal:
        """Generate a doctrine page update proposal."""
        target = "site/doctrine/index.html"
        body = (
            f"# Doctrine update\n\n"
            f"{event.body}\n\n"
            f"## Witness\n\n"
            f"- Source: [{event.repo}@{event.timestamp}]({event.url})\n"
        )
        proposal = ContentProposal(
            proposal_id=f"prop-{int(datetime.now(timezone.utc).timestamp())}-doctrine",
            target_path=target,
            title=f"Doctrine: {event.title}",
            body=body,
            source_event=event,
            kind="doctrine_clarification",
            witnesses=[event.url],
        )
        self.proposals.append(proposal)
        return proposal

    def route_event(self, event: GHEvent) -> Optional[ContentProposal]:
        """Route a GH event to the right proposal kind."""
        if event.event_type == "release":
            return self.propose_fleet_entry(event)
        elif event.event_type == "pr_merged" and "doctrine" in event.title.lower():
            return self.propose_doctrine_update(event)
        elif event.event_type in ("pr_merged", "release", "witness_emitted"):
            return self.propose_changelog_entry(event)
        elif event.event_type == "issue_opened":
            # Could become a diamond-rough entry; for now skip
            return None
        return None

    def stage_pr(self, proposal: ContentProposal) -> Dict[str, Any]:
        """Stage the proposal as a PR on the site repo.

        In production: this opens a real GH PR.
        In v0.1: returns the proposal payload for the orchestrator.
        """
        return {
            "branch": f"gen/{proposal.proposal_id}",
            "files": [{"path": proposal.target_path, "content": proposal.body}],
            "pr_title": f"[gen] {proposal.title}",
            "pr_body": (
                f"Auto-generated by the GAN pipeline.\n\n"
                f"**Source event**: {proposal.source_event.url}\n\n"
                f"**Witnesses**: {', '.join(proposal.witnesses)}\n\n"
                f"FNV1a-64 canary: 0x24a555471370b18d\n"
            ),
            "labels": ["gan-generated", "needs-adversary-review"],
        }


# Convenience CLI

def main():
    import json
    import sys

    gen = Generator()

    # Demo: process a sample event
    sample = GHEvent(
        event_type="release",
        repo="SuperInstance/quilt-port",
        title="quilt-port v0.1.0",
        url="https://github.com/SuperInstance/quilt-port/releases/tag/v0.1.0",
        body="Initial scaffold of quilt-port — the user's port to their quilts.",
    )
    proposal = gen.route_event(sample)
    if proposal:
        print(json.dumps(proposal.to_dict(), indent=2))
        print("\nPR staging:")
        print(json.dumps(gen.stage_pr(proposal), indent=2))


if __name__ == "__main__":
    main()
